### ISSUE TITLE
Instructions? 

### ISSUE THREAD

**Issue by masters3d** [AtomLinter/linter-swiftc#1]
How do you work this on Atom? Reading the code I see that it needs "linter" ? 

Do i need to have node and coffee script installed for this to work with atom?

Thanks!

**Comment by k2b6s9j** [comment]
You do not need Node and CoffeeScript for this to work with Atom, since Atom is built on Node and CoffeeScript. I will update the README to include instructions on setting up the plugin.

**Comment by masters3d** [comment]
Cool. Thank you!
