### ISSUE TITLE
How to make it know about the UIKit module?

### ISSUE THREAD

**Issue by pbernery** [AtomLinter/linter-swiftc#13]
I just installed linter-switfc and after saving a file (the AppDelegate.swift file), the linter complains with "no such module 'UIKit'".

Can linter-swiftc work with this kind of import?

**Comment by kepler0** [comment]
Yes, it must be defined to as a command line option in the settings. However, it seems that you are attempting to use this for an iOS project. Instead of using `linter-swiftc` I'd recommend looking toward the [`build` package](https://atombuild.github.io) for integration with your Xcode project.

**Comment by pbernery** [comment]
Thank you for your feedback @kepler0.
Can the build package show Swift compiler warning/errors without starting a build manually? I thought linter-swiftc was meant to reproduce Xcode behavior while editing Swift code.

**Comment by affanshahid** [comment]
Getting "no such module ..." on all imports, what command Line options do I need?
