### ISSUE TITLE
Does this offer suggestions on style?

### ISSUE THREAD

**Issue by masters3d** [AtomLinter/linter-swiftc#2]
For example: { } Style? I know there are not standards yet for swift but some people seem to prefer using the c# style of {}  instead of the more readable 
https://github.com/raywenderlich/swift-style-guide

**Comment by k2b6s9j** [comment]
This plugin simple runs your file through the Swift compiler to find any errors or warnings it might produce. As far as I know the Swift compiler does not offer any style warnings.

**Comment by masters3d** [comment]
Oh ok. So if I am already using xcode then I won't benefit. I was confused
on what linter was meant to do.

What are you thoughts if all I wanted was to get my curly braces to line up
a certain way?

Thanks!

**Comment by k2b6s9j** [comment]
So this is a plugin for [Atom](https://atom.io/). If you are content with using Xcode for your Text Editor and IDE this really isn't the plugin for you.

But, when you say line up do you just want Xcode to assist you with styling? I believe there is a way to go about this using Xcode.

**Comment by k2b6s9j** [comment]
@masters3d You're probably looking for [linter-swiftlint](https://github.com/k2b6s9j/linter-swiftlint) and [SwiftLint](https://github.com/realm/SwiftLint).
